# Generated by Django 5.1.7 on 2025-03-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "type_house",
                    models.CharField(
                        choices=[
                            ("apartment", "Квартира"),
                            ("house", "Частный дом"),
                            ("cottage", "Дача"),
                        ],
                        max_length=20,
                        verbose_name="Тип жилья",
                    ),
                ),
                (
                    "electrical_appliances",
                    models.TextField(
                        help_text="Перечислите технику через запятую",
                        verbose_name="Бытовая техника",
                    ),
                ),
                (
                    "people",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_data",
                        to="app.people",
                        verbose_name="Человек",
                    ),
                ),
            ],
        ),
    ]
